---
name: Run zenload
author: Stefan Aeschbacher
description: runs different loop optimization tests in python and c
architecture: linux
services:
  cpu-load:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpu-load-container
    image: cpu-load-container:latest

flow:
  - name: Loop-Test
    container: cpu-load-container
    commands:
      - type: console
        command: python3 loop.py
        note: running python
      - type: console
        command: hash_unoptimized
        note: running unoptimized c
      - type: console
        command: hash_optimized
        note: running optimized c
